#!/bin/bash
# Generated by tools/language_health.py
set -e
echo 'Disabling WikiAfr.gf (File WikiI.gf does not exist.)'
mv gf/WikiAfr.gf gf/WikiAfr.gf.SKIP
echo 'Disabling WikiAmh.gf (File WikiI.gf does not exist.)'
mv gf/WikiAmh.gf gf/WikiAmh.gf.SKIP
echo 'Disabling WikiAra.gf (File WikiI.gf does not exist.)'
mv gf/WikiAra.gf gf/WikiAra.gf.SKIP
echo 'Disabling WikiBel.gf (File Wiki.gf does not exist.)'
mv gf/WikiBel.gf gf/WikiBel.gf.SKIP
echo 'Disabling WikiBul.gf (File WikiI.gf does not exist.)'
mv gf/WikiBul.gf gf/WikiBul.gf.SKIP
echo 'Disabling WikiCat.gf (File WikiI.gf does not exist.)'
mv gf/WikiCat.gf gf/WikiCat.gf.SKIP
echo 'Disabling WikiCgg.gf (File Wiki.gf does not exist.)'
mv gf/WikiCgg.gf gf/WikiCgg.gf.SKIP
echo 'Disabling WikiChi.gf (File Wiki.gf does not exist.)'
mv gf/WikiChi.gf gf/WikiChi.gf.SKIP
echo 'Disabling WikiCze.gf (File Wiki.gf does not exist.)'
mv gf/WikiCze.gf gf/WikiCze.gf.SKIP
echo 'Disabling WikiDan.gf (File WikiI.gf does not exist.)'
mv gf/WikiDan.gf gf/WikiDan.gf.SKIP
echo 'Disabling WikiDeu.gf (File WikiI.gf does not exist.)'
mv gf/WikiDeu.gf gf/WikiDeu.gf.SKIP
echo 'Disabling WikiDut.gf (File Wiki.gf does not exist.)'
mv gf/WikiDut.gf gf/WikiDut.gf.SKIP
echo 'Disabling WikiEll.gf (File WikiI.gf does not exist.)'
mv gf/WikiEll.gf gf/WikiEll.gf.SKIP
echo 'Disabling WikiEng.gf ([34m)'
mv gf/WikiEng.gf gf/WikiEng.gf.SKIP
echo 'Disabling WikiEst.gf (File WikiI.gf does not exist.)'
mv gf/WikiEst.gf gf/WikiEst.gf.SKIP
echo 'Disabling WikiEus.gf (File WikiI.gf does not exist.)'
mv gf/WikiEus.gf gf/WikiEus.gf.SKIP
echo 'Disabling WikiExt.gf (File Wiki.gf does not exist.)'
mv gf/WikiExt.gf gf/WikiExt.gf.SKIP
echo 'Disabling WikiFao.gf (File Wiki.gf does not exist.)'
mv gf/WikiFao.gf gf/WikiFao.gf.SKIP
echo 'Disabling WikiFas.gf (File WikiI.gf does not exist.)'
mv gf/WikiFas.gf gf/WikiFas.gf.SKIP
echo 'Disabling WikiFin.gf (File WikiI.gf does not exist.)'
mv gf/WikiFin.gf gf/WikiFin.gf.SKIP
echo 'Disabling WikiFra.gf ([34m)'
mv gf/WikiFra.gf gf/WikiFra.gf.SKIP
echo 'Disabling WikiGer.gf (File WikiI.gf does not exist.)'
mv gf/WikiGer.gf gf/WikiGer.gf.SKIP
echo 'Disabling WikiGla.gf (File Wiki.gf does not exist.)'
mv gf/WikiGla.gf gf/WikiGla.gf.SKIP
echo 'Disabling WikiGrc.gf (File Wiki.gf does not exist.)'
mv gf/WikiGrc.gf gf/WikiGrc.gf.SKIP
echo 'Disabling WikiGre.gf (File Wiki.gf does not exist.)'
mv gf/WikiGre.gf gf/WikiGre.gf.SKIP
echo 'Disabling WikiGus.gf (File Wiki.gf does not exist.)'
mv gf/WikiGus.gf gf/WikiGus.gf.SKIP
echo 'Disabling WikiHeb.gf (File WikiI.gf does not exist.)'
mv gf/WikiHeb.gf gf/WikiHeb.gf.SKIP
echo 'Disabling WikiHin.gf (File WikiI.gf does not exist.)'
mv gf/WikiHin.gf gf/WikiHin.gf.SKIP
echo 'Disabling WikiHrv.gf (File Wiki.gf does not exist.)'
mv gf/WikiHrv.gf gf/WikiHrv.gf.SKIP
echo 'Disabling WikiHun.gf (File WikiI.gf does not exist.)'
mv gf/WikiHun.gf gf/WikiHun.gf.SKIP
echo 'Disabling WikiHye.gf (File Wiki.gf does not exist.)'
mv gf/WikiHye.gf gf/WikiHye.gf.SKIP
echo 'Disabling WikiIce.gf (File Wiki.gf does not exist.)'
mv gf/WikiIce.gf gf/WikiIce.gf.SKIP
echo 'Disabling WikiIna.gf (File Wiki.gf does not exist.)'
mv gf/WikiIna.gf gf/WikiIna.gf.SKIP
echo 'Disabling WikiIsl.gf (File WikiI.gf does not exist.)'
mv gf/WikiIsl.gf gf/WikiIsl.gf.SKIP
echo 'Disabling WikiIta.gf (File WikiI.gf does not exist.)'
mv gf/WikiIta.gf gf/WikiIta.gf.SKIP
echo 'Disabling WikiJpn.gf (File WikiI.gf does not exist.)'
mv gf/WikiJpn.gf gf/WikiJpn.gf.SKIP
echo 'Disabling WikiKam.gf (File Wiki.gf does not exist.)'
mv gf/WikiKam.gf gf/WikiKam.gf.SKIP
echo 'Disabling WikiKaz.gf (File Wiki.gf does not exist.)'
mv gf/WikiKaz.gf gf/WikiKaz.gf.SKIP
echo 'Disabling WikiKor.gf (File WikiI.gf does not exist.)'
mv gf/WikiKor.gf gf/WikiKor.gf.SKIP
echo 'Disabling WikiLat.gf (File WikiI.gf does not exist.)'
mv gf/WikiLat.gf gf/WikiLat.gf.SKIP
echo 'Disabling WikiLav.gf (File WikiI.gf does not exist.)'
mv gf/WikiLav.gf gf/WikiLav.gf.SKIP
echo 'Disabling WikiLit.gf (File WikiI.gf does not exist.)'
mv gf/WikiLit.gf gf/WikiLit.gf.SKIP
echo 'Disabling WikiMay.gf (File Wiki.gf does not exist.)'
mv gf/WikiMay.gf gf/WikiMay.gf.SKIP
echo 'Disabling WikiMkd.gf (File Wiki.gf does not exist.)'
mv gf/WikiMkd.gf gf/WikiMkd.gf.SKIP
echo 'Disabling WikiMlt.gf (File WikiI.gf does not exist.)'
mv gf/WikiMlt.gf gf/WikiMlt.gf.SKIP
echo 'Disabling WikiMon.gf (File WikiI.gf does not exist.)'
mv gf/WikiMon.gf gf/WikiMon.gf.SKIP
echo 'Disabling WikiNep.gf (File WikiI.gf does not exist.)'
mv gf/WikiNep.gf gf/WikiNep.gf.SKIP
echo 'Disabling WikiNld.gf (File WikiI.gf does not exist.)'
mv gf/WikiNld.gf gf/WikiNld.gf.SKIP
echo 'Disabling WikiNno.gf (File WikiI.gf does not exist.)'
mv gf/WikiNno.gf gf/WikiNno.gf.SKIP
echo 'Disabling WikiNob.gf (File WikiI.gf does not exist.)'
mv gf/WikiNob.gf gf/WikiNob.gf.SKIP
echo 'Disabling WikiNor.gf (File Wiki.gf does not exist.)'
mv gf/WikiNor.gf gf/WikiNor.gf.SKIP
echo 'Disabling WikiPan.gf (File WikiI.gf does not exist.)'
mv gf/WikiPan.gf gf/WikiPan.gf.SKIP
echo 'Disabling WikiPes.gf (File Wiki.gf does not exist.)'
mv gf/WikiPes.gf gf/WikiPes.gf.SKIP
echo 'Disabling WikiPnb.gf (File Wiki.gf does not exist.)'
mv gf/WikiPnb.gf gf/WikiPnb.gf.SKIP
echo 'Disabling WikiPol.gf (File WikiI.gf does not exist.)'
mv gf/WikiPol.gf gf/WikiPol.gf.SKIP
echo 'Disabling WikiPor.gf (File WikiI.gf does not exist.)'
mv gf/WikiPor.gf gf/WikiPor.gf.SKIP
echo 'Disabling WikiRon.gf (File WikiI.gf does not exist.)'
mv gf/WikiRon.gf gf/WikiRon.gf.SKIP
echo 'Disabling WikiRus.gf (File WikiI.gf does not exist.)'
mv gf/WikiRus.gf gf/WikiRus.gf.SKIP
echo 'Disabling WikiSco.gf (File Wiki.gf does not exist.)'
mv gf/WikiSco.gf gf/WikiSco.gf.SKIP
echo 'Disabling WikiSlo.gf (File Wiki.gf does not exist.)'
mv gf/WikiSlo.gf gf/WikiSlo.gf.SKIP
echo 'Disabling WikiSlv.gf (File WikiI.gf does not exist.)'
mv gf/WikiSlv.gf gf/WikiSlv.gf.SKIP
echo 'Disabling WikiSnd.gf (File WikiI.gf does not exist.)'
mv gf/WikiSnd.gf gf/WikiSnd.gf.SKIP
echo 'Disabling WikiSpa.gf (File WikiI.gf does not exist.)'
mv gf/WikiSpa.gf gf/WikiSpa.gf.SKIP
echo 'Disabling WikiSqi.gf (File Wiki.gf does not exist.)'
mv gf/WikiSqi.gf gf/WikiSqi.gf.SKIP
echo 'Disabling WikiSwe.gf (File WikiI.gf does not exist.)'
mv gf/WikiSwe.gf gf/WikiSwe.gf.SKIP
echo 'Disabling WikiTam.gf (File Wiki.gf does not exist.)'
mv gf/WikiTam.gf gf/WikiTam.gf.SKIP
echo 'Disabling WikiTel.gf (File Wiki.gf does not exist.)'
mv gf/WikiTel.gf gf/WikiTel.gf.SKIP
echo 'Disabling WikiTha.gf (File WikiI.gf does not exist.)'
mv gf/WikiTha.gf gf/WikiTha.gf.SKIP
echo 'Disabling WikiTur.gf (File WikiI.gf does not exist.)'
mv gf/WikiTur.gf gf/WikiTur.gf.SKIP
echo 'Disabling WikiUkr.gf (File Wiki.gf does not exist.)'
mv gf/WikiUkr.gf gf/WikiUkr.gf.SKIP
echo 'Disabling WikiUrd.gf (File WikiI.gf does not exist.)'
mv gf/WikiUrd.gf gf/WikiUrd.gf.SKIP
echo 'Disabling WikiZho.gf (File WikiI.gf does not exist.)'
mv gf/WikiZho.gf gf/WikiZho.gf.SKIP
