#!/bin/bash
# Generated by tools/language_health.py
set -e
cd "$(dirname "$0")"
echo 'Disabling generated/src/WikiEng.gf (File Prelude.gf does not exist.)'
if [ -f 'generated/src/WikiEng.gf' ]; then mv 'generated/src/WikiEng.gf' 'generated/src/WikiEng.gf.SKIP'; fi
echo 'Disabling generated/src/WikiFre.gf (File Prelude.gf does not exist.)'
if [ -f 'generated/src/WikiFre.gf' ]; then mv 'generated/src/WikiFre.gf' 'generated/src/WikiFre.gf.SKIP'; fi
