#!/bin/bash
# Generated by tools/language_health
set -e
cd "$(dirname "$0")"
echo 'Disabling gf/WikiEng.gf (gf/WikiEng.gf:)'
if [ -f gf/WikiEng.gf ]; then mv gf/WikiEng.gf gf/WikiEng.gf.SKIP; fi
echo 'Disabling gf/WikiFre.gf (gf/WikiFre.gf:)'
if [ -f gf/WikiFre.gf ]; then mv gf/WikiFre.gf gf/WikiFre.gf.SKIP; fi
