# architect_http_api/config_gf.py
# =========================================================================
# GF CONFIGURATION: Paths and Settings
#
# This module defines the global configuration for the Grammatical Framework
# integration, including file paths and language preferences.
# =========================================================================

import os

# --- BASE DIRECTORIES ---
# The root directory of the 'architect_http_api' package
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# The project root (one level up from 'architect_http_api')
PROJECT_ROOT = os.path.dirname(BASE_DIR)

# --- FILE PATHS ---

# Path to the compiled PGF binary (The artifact generated by 'gf/build_orchestrator.py')
# 
# 1. Environment Variable: Best for Docker/Production (e.g. /app/gf/Wiki.pgf)
# 2. Local Fallback: Relative to the source code (for local dev)
env_pgf_path = os.getenv("AW_PGF_PATH")

if env_pgf_path:
    PGF_FILE_PATH = env_pgf_path
else:
    PGF_FILE_PATH = os.path.join(PROJECT_ROOT, "gf", "Wiki.pgf")

# Path to the GF source directory (where AbstractWiki.gf lives)
GF_SOURCE_DIR = os.path.join(PROJECT_ROOT, "gf")

# --- LANGUAGE SETTINGS ---

# The default language to use if none is specified in an API call
DEFAULT_LANGUAGE = "eng"  # English

# A list of 'Core' languages that should always be validated during tests
# or prioritized in UI dropdowns.
PRIORITY_LANGUAGES = [
    "eng", # English
    "fra", # French
    "deu", # German
    "spa", # Spanish
    "zho", # Chinese
    "ara", # Arabic
    "rus", # Russian
]

# --- BUILD CONFIGURATION ---

# If your system uses a custom location for the RGL (Resource Grammar Library),
# set it here. Otherwise, the build script assumes standard system install.
# Example: "/usr/local/share/gf-4.1/lib"
RGL_LIBRARY_PATH = os.environ.get("GF_LIB_PATH", None)

# Compiler flags for the 'gf' command
# -v = verbose, -s = silent, --optimize-pgf = smaller binary
GF_COMPILER_FLAGS = ["-v", "--optimize-pgf"]