from __future__ import annotations

from typing import Dict, Sequence, Tuple

from .config import DEFAULT_TIMEOUT_SEC, PYTHON_EXE
from .models import ToolSpec


def _wf(*names: str) -> Tuple[str, ...]:
    seen = set()
    out = []
    for name in names:
        v = (name or "").strip()
        if not v or v in seen:
            continue
        seen.add(v)
        out.append(v)
    if "all" not in seen:
        out.append("all")
    return tuple(out)


def py_script(
    tool_id: str,
    rel_script: str,
    description: str,
    *,
    timeout_sec: int = DEFAULT_TIMEOUT_SEC,
    allow_args: bool = False,
    allowed_flags: Sequence[str] = (),
    allow_positionals: bool = False,
    requires_ai_enabled: bool = False,
    flags_with_value: Sequence[str] = (),
    flags_with_multi_value: Sequence[str] = (),
    category: str = "qa",
    hidden: bool = False,
    internal: bool = False,
    heavy: bool = False,
    legacy: bool = False,
    is_test: bool = False,
    workflow_tags: Sequence[str] = (),
) -> ToolSpec:
    return ToolSpec(
        tool_id=tool_id,
        description=description,
        rel_target=rel_script,
        cmd=(PYTHON_EXE, "-u", "{target}"),
        timeout_sec=timeout_sec,
        allow_args=allow_args,
        allowed_flags=tuple(allowed_flags),
        allow_positionals=allow_positionals,
        requires_ai_enabled=requires_ai_enabled,
        flags_with_value=tuple(flags_with_value),
        flags_with_multi_value=tuple(flags_with_multi_value),
        category=category,
        hidden=hidden,
        internal=internal,
        heavy=heavy,
        legacy=legacy,
        is_test=is_test,
        workflow_tags=tuple(workflow_tags),
    )


def pytest_file(
    tool_id: str,
    rel_test_file: str,
    description: str,
    *,
    timeout_sec: int = DEFAULT_TIMEOUT_SEC,
    allow_args: bool = False,
    allowed_flags: Sequence[str] = (),
    flags_with_value: Sequence[str] = (),
    category: str = "qa",
    hidden: bool = True,
    internal: bool = False,
    heavy: bool = False,
    legacy: bool = False,
    workflow_tags: Sequence[str] = (),
) -> ToolSpec:
    return ToolSpec(
        tool_id=tool_id,
        description=description,
        rel_target=rel_test_file,
        cmd=(PYTHON_EXE, "-u", "-m", "pytest", "{target}"),
        timeout_sec=timeout_sec,
        allow_args=allow_args,
        allowed_flags=tuple(allowed_flags),
        allow_positionals=False,
        requires_ai_enabled=False,
        flags_with_value=tuple(flags_with_value),
        flags_with_multi_value=(),
        category=category,
        hidden=hidden,
        internal=internal,
        heavy=heavy,
        legacy=legacy,
        is_test=True,
        workflow_tags=tuple(workflow_tags),
    )


def qa_registry() -> Dict[str, ToolSpec]:
    return {
        "ambiguity_detector": py_script(
            "ambiguity_detector",
            "tools/qa/ambiguity_detector.py",
            "Uses AI to generate ambiguous sentences and checks for multiple parse trees.",
            timeout_sec=1200,
            allow_args=True,
            allowed_flags=("--lang", "--sentence", "--topic", "--json-out", "--verbose"),
            allow_positionals=False,
            requires_ai_enabled=True,
            flags_with_value=("--lang", "--sentence", "--topic", "--json-out"),
            category="qa",
            hidden=True,
            heavy=True,
            workflow_tags=_wf("qa_validation", "debug_recovery", "ai_assist"),
        ),
        "run_smoke_tests": pytest_file(
            "run_smoke_tests",
            "tests/test_lexicon_smoke.py",
            "Lexicon schema and syntax smoke tests.",
            timeout_sec=900,
            allow_args=True,
            allowed_flags=("-q", "-vv", "-k", "-m", "--maxfail", "--disable-warnings"),
            flags_with_value=("-k", "-m", "--maxfail"),
            category="qa",
            hidden=True,
            workflow_tags=_wf("qa_validation", "debug_recovery"),
        ),
        "run_judge": pytest_file(
            "run_judge",
            "tests/integration/test_quality.py",
            "Executes golden-standard regression checks (AI Judge integration).",
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=("-q", "-vv", "-k", "-m", "--maxfail", "--disable-warnings"),
            flags_with_value=("-k", "-m", "--maxfail"),
            category="qa",
            hidden=False,
            heavy=True,
            workflow_tags=_wf("recommended", "language_integration", "qa_validation"),
        ),
        "eval_bios": py_script(
            "eval_bios",
            "tools/qa/eval_bios.py",
            "Compares generated biographies against Wikidata facts.",
            timeout_sec=1200,
            allow_args=True,
            allowed_flags=("--langs", "--limit", "--out", "--verbose"),
            allow_positionals=False,
            flags_with_value=("--limit", "--out"),
            flags_with_multi_value=("--langs",),
            category="qa",
            hidden=True,
            workflow_tags=_wf("qa_validation"),
        ),
        "lexicon_coverage": py_script(
            "lexicon_coverage",
            "tools/qa/lexicon_coverage_report.py",
            "Coverage report for intended vs implemented lexicon.",
            timeout_sec=1200,
            allow_args=True,
            allowed_flags=(
                "--lexicon-dir",
                "--lang",
                "--target-core",
                "--target-conc",
                "--target-bio",
                "--out",
                "--no-md",
                "--include-files",
                "--fail-on-errors",
            ),
            allow_positionals=False,
            flags_with_value=(
                "--lexicon-dir",
                "--lang",
                "--target-core",
                "--target-conc",
                "--target-bio",
                "--out",
            ),
            flags_with_multi_value=(),
            category="data",
            hidden=False,
            workflow_tags=_wf("recommended", "language_integration", "lexicon_work"),
        ),
        "universal_test_runner": py_script(
            "universal_test_runner",
            "tools/qa/universal_test_runner.py",
            "Advanced CSV test runner for more complex constructions.",
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=(
                "--dataset-dir",
                "--pattern",
                "--langs",
                "--limit",
                "--fail-fast",
                "--strict",
                "--print-failures",
                "--json-report",
                "--verbose",
                "--pgf",
                "--diagnose",
                "--list-languages",
            ),
            allow_positionals=False,
            flags_with_value=(
                "--dataset-dir",
                "--pattern",
                "--langs",
                "--limit",
                "--print-failures",
                "--json-report",
                "--pgf",
            ),
            flags_with_multi_value=(),
            category="qa",
            hidden=True,
            heavy=True,
            workflow_tags=_wf("qa_validation", "debug_recovery"),
        ),
        "test_runner": py_script(
            "test_runner",
            "tools/qa/universal_test_runner.py",
            "Legacy alias for universal_test_runner.",
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=(
                "--dataset-dir",
                "--pattern",
                "--langs",
                "--limit",
                "--fail-fast",
                "--strict",
                "--print-failures",
                "--json-report",
                "--verbose",
                "--pgf",
                "--diagnose",
                "--list-languages",
            ),
            allow_positionals=False,
            flags_with_value=(
                "--dataset-dir",
                "--pattern",
                "--langs",
                "--limit",
                "--print-failures",
                "--json-report",
                "--pgf",
            ),
            flags_with_multi_value=(),
            category="qa",
            hidden=True,
            heavy=True,
            legacy=True,
            workflow_tags=_wf("qa_validation", "debug_recovery"),
        ),
        "batch_test_generator": py_script(
            "batch_test_generator",
            "tools/qa/batch_test_generator.py",
            "Bulk generation of test datasets for regression.",
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=("--langs", "--out", "--limit", "--seed", "--verbose"),
            allow_positionals=False,
            flags_with_value=("--out", "--limit", "--seed"),
            flags_with_multi_value=("--langs",),
            category="qa",
            hidden=True,
            heavy=True,
            workflow_tags=_wf("qa_validation"),
        ),
        "test_suite_generator": py_script(
            "test_suite_generator",
            "tools/qa/test_suite_generator.py",
            "Generates empty CSV templates for manual or AI fill-in.",
            timeout_sec=900,
            allow_args=True,
            allowed_flags=("--langs", "--out", "--verbose"),
            allow_positionals=False,
            flags_with_value=("--out",),
            flags_with_multi_value=("--langs",),
            category="qa",
            hidden=True,
            workflow_tags=_wf("qa_validation"),
        ),
        "generate_lexicon_regression_tests": py_script(
            "generate_lexicon_regression_tests",
            "tools/qa/generate_lexicon_regression_tests.py",
            "Builds regression tests from lexicon for CI and QA.",
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=("--langs", "--out", "--limit", "--verbose", "--lexicon-dir"),
            allow_positionals=False,
            flags_with_value=("--out", "--limit", "--lexicon-dir"),
            flags_with_multi_value=("--langs",),
            category="qa",
            hidden=True,
            heavy=True,
            workflow_tags=_wf("lexicon_work", "qa_validation"),
        ),
        "seed_lexicon": py_script(
            "seed_lexicon",
            "utils/seed_lexicon_ai.py",
            "Uses AI to generate core vocabulary for new languages.",
            timeout_sec=3600,
            allow_args=True,
            allowed_flags=("--langs", "--limit", "--dry-run", "--verbose"),
            allow_positionals=False,
            requires_ai_enabled=True,
            flags_with_value=("--limit",),
            flags_with_multi_value=("--langs",),
            category="ai",
            hidden=True,
            heavy=True,
            workflow_tags=_wf("lexicon_work", "ai_assist"),
        ),
        "ai_refiner": py_script(
            "ai_refiner",
            "tools/ai_refiner.py",
            "Attempts to upgrade Pidgin grammars to full RGL.",
            timeout_sec=3600,
            allow_args=True,
            allowed_flags=("--langs", "--dry-run", "--verbose"),
            allow_positionals=True,
            requires_ai_enabled=True,
            flags_with_multi_value=("--langs",),
            category="ai",
            hidden=True,
            heavy=True,
            workflow_tags=_wf("language_integration", "debug_recovery", "ai_assist"),
        ),
        "test_api_smoke": pytest_file(
            "test_api_smoke",
            "tests/test_api_smoke.py",
            "API smoke tests (fast signal).",
            timeout_sec=600,
            allow_args=True,
            allowed_flags=("-q", "-vv", "-k", "-m", "--maxfail", "--disable-warnings"),
            flags_with_value=("-k", "-m", "--maxfail"),
            category="qa",
            hidden=True,
            workflow_tags=_wf("qa_validation", "debug_recovery"),
        ),
        "test_gf_dynamic": pytest_file(
            "test_gf_dynamic",
            "tests/test_gf_dynamic.py",
            "Validates dynamic loading and linearization of GF grammars.",
            timeout_sec=900,
            allow_args=True,
            allowed_flags=("-q", "-vv", "-k", "-m", "--maxfail", "--disable-warnings"),
            flags_with_value=("-k", "-m", "--maxfail"),
            category="qa",
            hidden=True,
            workflow_tags=_wf("qa_validation", "debug_recovery"),
        ),
        "test_multilingual_generation": pytest_file(
            "test_multilingual_generation",
            "tests/test_multilingual_generation.py",
            "Multilingual generation regression tests.",
            timeout_sec=1200,
            allow_args=True,
            allowed_flags=("-q", "-vv", "-k", "-m", "--maxfail", "--disable-warnings"),
            flags_with_value=("-k", "-m", "--maxfail"),
            category="qa",
            hidden=True,
            workflow_tags=_wf("qa_validation", "debug_recovery"),
        ),
    }