from __future__ import annotations

from typing import Dict, Sequence

from .config import DEFAULT_TIMEOUT_SEC, PYTHON_EXE
from .models import ToolSpec


def _supports_flag(flag: str, allowed_flags: Sequence[str]) -> bool:
    return flag in set(allowed_flags)


def _is_heavy(risk: str) -> bool:
    return (risk or "").strip().lower() == "heavy"


def py_script(
    tool_id: str,
    rel_script: str,
    description: str,
    *,
    title: str,
    category: str,
    group: str,
    risk: str = "safe",
    hidden: bool = False,
    workflow_tags: Sequence[str] = (),
    timeout_sec: int = DEFAULT_TIMEOUT_SEC,
    allow_args: bool = False,
    allowed_flags: Sequence[str] = (),
    allow_positionals: bool = False,
    requires_ai_enabled: bool = False,
    flags_with_value: Sequence[str] = (),
    flags_with_multi_value: Sequence[str] = (),
    supports_verbose: bool | None = None,
    supports_json: bool | None = None,
) -> ToolSpec:
    _ = group
    _ = supports_verbose
    _ = supports_json

    return ToolSpec(
        tool_id=tool_id,
        description=description,
        rel_target=rel_script,
        cmd=(PYTHON_EXE, "-u", "{target}"),
        timeout_sec=timeout_sec,
        allow_args=allow_args,
        allowed_flags=tuple(allowed_flags),
        allow_positionals=allow_positionals,
        requires_ai_enabled=requires_ai_enabled,
        flags_with_value=tuple(flags_with_value),
        flags_with_multi_value=tuple(flags_with_multi_value),
        label=title,
        category=category,
        hidden=hidden,
        heavy=_is_heavy(risk),
        workflow_tags=tuple(workflow_tags),
    )


def py_module(
    tool_id: str,
    module: str,
    rel_check_path: str,
    description: str,
    *,
    title: str,
    category: str,
    group: str,
    risk: str = "safe",
    hidden: bool = False,
    workflow_tags: Sequence[str] = (),
    timeout_sec: int = DEFAULT_TIMEOUT_SEC,
    allow_args: bool = False,
    allowed_flags: Sequence[str] = (),
    allow_positionals: bool = False,
    requires_ai_enabled: bool = False,
    flags_with_value: Sequence[str] = (),
    flags_with_multi_value: Sequence[str] = (),
    supports_verbose: bool | None = None,
    supports_json: bool | None = None,
) -> ToolSpec:
    _ = group
    _ = supports_verbose
    _ = supports_json

    return ToolSpec(
        tool_id=tool_id,
        description=description,
        rel_target=rel_check_path,
        cmd=(PYTHON_EXE, "-u", "-m", module),
        timeout_sec=timeout_sec,
        allow_args=allow_args,
        allowed_flags=tuple(allowed_flags),
        allow_positionals=allow_positionals,
        requires_ai_enabled=requires_ai_enabled,
        flags_with_value=tuple(flags_with_value),
        flags_with_multi_value=tuple(flags_with_multi_value),
        label=title,
        category=category,
        hidden=hidden,
        heavy=_is_heavy(risk),
        workflow_tags=tuple(workflow_tags),
    )


def build_registry() -> Dict[str, ToolSpec]:
    return {
        # --- BUILD SYSTEM / EVERYTHING MATRIX ---
        "build_index": py_script(
            "build_index",
            "tools/everything_matrix/build_index.py",
            "Rebuilds everything_matrix.json by scanning repo (languages, lexicon, QA).",
            title="Rebuild Everything Matrix",
            category="Build System",
            group="Everything Matrix",
            risk="moderate",
            workflow_tags=("recommended", "language_integration", "lexicon_work", "build_matrix"),
            timeout_sec=900,
            allow_args=True,
            allowed_flags=(
                "--out",
                "--verbose",
                "--langs",
                "--force",
                "--regen-rgl",
                "--regen-lex",
                "--regen-app",
                "--regen-qa",
            ),
            allow_positionals=False,
            flags_with_value=("--out",),
            flags_with_multi_value=("--langs",),
        ),
        "app_scanner": py_script(
            "app_scanner",
            "tools/everything_matrix/app_scanner.py",
            "Scans app/frontend/backend surfaces for language support signals.",
            title="App Scanner",
            category="Build System",
            group="Everything Matrix",
            risk="safe",
            hidden=True,
            workflow_tags=("build_matrix", "debug_recovery"),
            timeout_sec=600,
            supports_json=True,
        ),
        "lexicon_scanner": py_script(
            "lexicon_scanner",
            "tools/everything_matrix/lexicon_scanner.py",
            "Scores lexicon maturity by scanning shard coverage.",
            title="Lexicon Scanner",
            category="Build System",
            group="Everything Matrix",
            risk="safe",
            hidden=True,
            workflow_tags=("build_matrix", "debug_recovery", "lexicon_work"),
            timeout_sec=600,
            supports_json=True,
        ),
        "qa_scanner": py_script(
            "qa_scanner",
            "tools/everything_matrix/qa_scanner.py",
            "Parses QA output/logs to update quality scoring.",
            title="QA Scanner",
            category="Build System",
            group="Everything Matrix",
            risk="safe",
            hidden=True,
            workflow_tags=("build_matrix", "debug_recovery", "qa_validation"),
            timeout_sec=600,
            supports_json=True,
        ),
        "rgl_scanner": py_script(
            "rgl_scanner",
            "tools/everything_matrix/rgl_scanner.py",
            "Audits RGL grammar module presence/consistency.",
            title="RGL Scanner",
            category="Build System",
            group="Everything Matrix",
            risk="safe",
            hidden=True,
            workflow_tags=("build_matrix", "debug_recovery", "language_integration"),
            timeout_sec=600,
            supports_json=True,
        ),
        "compile_pgf": py_module(
            "compile_pgf",
            "builder.orchestrator",
            "builder/orchestrator/__main__.py",
            "Two-phase GF build orchestrator to produce semantik_architect.pgf.",
            title="Compile PGF (Build Orchestrator)",
            category="Build System",
            group="GF Build",
            risk="heavy",
            workflow_tags=("recommended", "language_integration", "build_matrix"),
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=(
                "--strategy",
                "--langs",
                "--clean",
                "--verbose",
                "--max-workers",
                "--no-preflight",
                "--regen-safe",
            ),
            allow_positionals=False,
            flags_with_value=("--strategy", "--max-workers"),
            flags_with_multi_value=("--langs",),
        ),
        "bootstrap_tier1": py_script(
            "bootstrap_tier1",
            "tools/bootstrap_tier1.py",
            "Bootstraps Tier 1 languages/wrappers.",
            title="Bootstrap Tier 1",
            category="Build System",
            group="GF Build",
            risk="moderate",
            hidden=True,
            workflow_tags=("language_integration", "build_matrix", "debug_recovery"),
            timeout_sec=1200,
            allow_args=True,
            allowed_flags=("--langs", "--force", "--dry-run", "--verbose"),
            allow_positionals=False,
            flags_with_multi_value=("--langs",),
        ),
        # --- LEXICON & DATA ---
        "gap_filler": py_script(
            "gap_filler",
            "tools/lexicon/gap_filler.py",
            "Identifies missing vocabulary by comparing Target vs Pivot language.",
            title="Lexicon Gap Filler",
            category="Lexicon & Data",
            group="Analysis",
            risk="safe",
            workflow_tags=("language_integration", "lexicon_work"),
            timeout_sec=600,
            allow_args=True,
            allowed_flags=("--target", "--pivot", "--data-dir", "--json-out", "--verbose"),
            allow_positionals=False,
            flags_with_value=("--target", "--pivot", "--data-dir", "--json-out"),
            supports_json=True,
        ),
        "harvest_lexicon": py_script(
            "harvest_lexicon",
            "tools/harvest_lexicon.py",
            "Universal Lexicon Harvester. Subcommands: `wordnet` and `wikidata` (positional).",
            title="Harvest Lexicon",
            category="Lexicon & Data",
            group="Mining & Harvesting",
            risk="moderate",
            workflow_tags=("language_integration", "lexicon_work"),
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=("--root", "--lang", "--out", "--input", "--domain"),
            allow_positionals=True,
            flags_with_value=("--root", "--lang", "--out", "--input", "--domain"),
        ),
        "build_lexicon_wikidata": py_script(
            "build_lexicon_wikidata",
            "utils/build_lexicon_from_wikidata.py",
            "Builds lexicon shards directly from Wikidata (online).",
            title="Build Lexicon from Wikidata",
            category="Lexicon & Data",
            group="Schema & Index",
            risk="moderate",
            hidden=True,
            workflow_tags=("lexicon_work", "debug_recovery"),
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=("--lang", "--out", "--limit", "--dry-run", "--verbose"),
            allow_positionals=False,
            flags_with_value=("--lang", "--out", "--limit"),
        ),
        "refresh_index": py_script(
            "refresh_index",
            "utils/refresh_lexicon_index.py",
            "Rebuilds the fast lexicon lookup index used by API.",
            title="Refresh Lexicon Index",
            category="Lexicon & Data",
            group="Schema & Index",
            risk="safe",
            hidden=True,
            workflow_tags=("lexicon_work", "debug_recovery"),
            timeout_sec=900,
            allow_args=True,
            allowed_flags=("--langs", "--root", "--out", "--verbose"),
            allow_positionals=False,
            flags_with_value=("--root", "--out"),
            flags_with_multi_value=("--langs",),
        ),
        "migrate_schema": py_script(
            "migrate_schema",
            "utils/migrate_lexicon_schema.py",
            "Migrates lexicon JSON shards to newer schema versions.",
            title="Migrate Lexicon Schema",
            category="Lexicon & Data",
            group="Schema & Index",
            risk="moderate",
            hidden=True,
            workflow_tags=("lexicon_work", "debug_recovery"),
            timeout_sec=1800,
            allow_args=True,
            allowed_flags=("--root", "--in-place", "--dry-run", "--from", "--to", "--verbose"),
            allow_positionals=False,
            flags_with_value=("--root", "--from", "--to"),
        ),
        "dump_stats": py_script(
            "dump_stats",
            "utils/dump_lexicon_stats.py",
            "Prints lexicon coverage/size statistics.",
            title="Dump Lexicon Stats",
            category="Lexicon & Data",
            group="Schema & Index",
            risk="safe",
            hidden=True,
            workflow_tags=("lexicon_work", "debug_recovery"),
            timeout_sec=600,
            allow_args=True,
            allowed_flags=("--langs", "--root", "--format", "--verbose"),
            allow_positionals=False,
            flags_with_value=("--root", "--format"),
            flags_with_multi_value=("--langs",),
        ),
    }