concrete WikiCat of Wiki = open SyntaxCat, (P = ParadigmsCat) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Cat

  lincat
    Phr = SyntaxCat.Phr ;
    NP  = SyntaxCat.NP ;
    CN  = SyntaxCat.CN ;
    Adv = SyntaxCat.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
