concrete WikiSlo of Wiki = open SyntaxSlo, (P = ParadigmsSlo) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Slo

  lincat
    Phr = SyntaxSlo.Phr ;
    NP  = SyntaxSlo.NP ;
    CN  = SyntaxSlo.CN ;
    Adv = SyntaxSlo.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
