concrete WikiUkr of Wiki = open GrammarUkr, (P = ParadigmsUkr) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Ukr

  lincat
    Phr = GrammarUkr.Phr ;
    NP  = GrammarUkr.NP ;
    CN  = GrammarUkr.CN ;
    Adv = GrammarUkr.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
