concrete WikiBul of Wiki = open SyntaxBul, (P = ParadigmsBul) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Bul

  lincat
    Phr = SyntaxBul.Phr ;
    NP  = SyntaxBul.NP ;
    CN  = SyntaxBul.CN ;
    Adv = SyntaxBul.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
