concrete WikiSwe of Wiki = open SyntaxSwe, (P = ParadigmsSwe) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Swe

  lincat
    Phr = SyntaxSwe.Phr ;
    NP  = SyntaxSwe.NP ;
    CN  = SyntaxSwe.CN ;
    Adv = SyntaxSwe.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
