concrete WikiEng of Wiki = open SyntaxEng, (P = ParadigmsEng) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Eng

  lincat
    Phr = SyntaxEng.Phr ;
    NP  = SyntaxEng.NP ;
    CN  = SyntaxEng.CN ;
    Adv = SyntaxEng.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
