concrete WikiLat of Wiki = open SyntaxLat, (P = ParadigmsLat) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Lat

  lincat
    Phr = SyntaxLat.Phr ;
    NP  = SyntaxLat.NP ;
    CN  = SyntaxLat.CN ;
    Adv = SyntaxLat.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
