concrete WikiIta of Wiki = open SyntaxIta, (P = ParadigmsIta) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Ita

  lincat
    Phr = SyntaxIta.Phr ;
    NP  = SyntaxIta.NP ;
    CN  = SyntaxIta.CN ;
    Adv = SyntaxIta.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
