concrete WikiFre of Wiki = open SyntaxFre, (P = ParadigmsFre) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Fre

  lincat
    Phr = SyntaxFre.Phr ;
    NP  = SyntaxFre.NP ;
    CN  = SyntaxFre.CN ;
    Adv = SyntaxFre.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
