concrete WikiPol of Wiki = open SyntaxPol, (P = ParadigmsPol) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Pol

  lincat
    Phr = SyntaxPol.Phr ;
    NP  = SyntaxPol.NP ;
    CN  = SyntaxPol.CN ;
    Adv = SyntaxPol.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
