concrete WikiGre of Wiki = open SyntaxGre, (P = ParadigmsGre) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Gre

  lincat
    Phr = SyntaxGre.Phr ;
    NP  = SyntaxGre.NP ;
    CN  = SyntaxGre.CN ;
    Adv = SyntaxGre.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
