concrete WikiPor of Wiki = open SyntaxPor, (P = ParadigmsPor) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Por

  lincat
    Phr = SyntaxPor.Phr ;
    NP  = SyntaxPor.NP ;
    CN  = SyntaxPor.CN ;
    Adv = SyntaxPor.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
