concrete WikiGrc of Wiki = open SyntaxGrc, (P = ParadigmsGrc) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Grc

  lincat
    Phr = SyntaxGrc.Phr ;
    NP  = SyntaxGrc.NP ;
    CN  = SyntaxGrc.CN ;
    Adv = SyntaxGrc.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
