concrete WikiTha of Wiki = open SyntaxTha, (P = ParadigmsTha) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Tha

  lincat
    Phr = SyntaxTha.Phr ;
    NP  = SyntaxTha.NP ;
    CN  = SyntaxTha.CN ;
    Adv = SyntaxTha.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
