concrete WikiGer of Wiki = open SyntaxGer, (P = ParadigmsGer) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Ger

  lincat
    Phr = SyntaxGer.Phr ;
    NP  = SyntaxGer.NP ;
    CN  = SyntaxGer.CN ;
    Adv = SyntaxGer.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
