concrete WikiExt of Wiki = open CatExt, NounExt in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: IRON
-- Language: Ext

  lincat
    Phr = CatExt.Phr ;
    NP  = CatExt.NP ;
    CN  = CatExt.CN ;
    Adv = CatExt.Adv ;

  lin
    SimpNP cn = MassNP cn ;
    
    John      = MassNP (UseN apple_N) ;
    Here      = cn ; 
    apple_N   = UseN apple_N ;
}
