concrete WikiLav of Wiki = open SyntaxLav, (P = ParadigmsLav) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Lav

  lincat
    Phr = SyntaxLav.Phr ;
    NP  = SyntaxLav.NP ;
    CN  = SyntaxLav.CN ;
    Adv = SyntaxLav.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
