concrete WikiNep of Wiki = open SyntaxNep, (P = ParadigmsNep) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Nep

  lincat
    Phr = SyntaxNep.Phr ;
    NP  = SyntaxNep.NP ;
    CN  = SyntaxNep.CN ;
    Adv = SyntaxNep.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
