concrete WikiSco of Wiki = open SyntaxSco, (P = ParadigmsSco) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Sco

  lincat
    Phr = SyntaxSco.Phr ;
    NP  = SyntaxSco.NP ;
    CN  = SyntaxSco.CN ;
    Adv = SyntaxSco.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
