concrete WikiFao of Wiki = open GrammarFao, (P = ParadigmsFao) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Fao

  lincat
    Phr = GrammarFao.Phr ;
    NP  = GrammarFao.NP ;
    CN  = GrammarFao.CN ;
    Adv = GrammarFao.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
