concrete WikiIce of Wiki = open SyntaxIce, (P = ParadigmsIce) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Ice

  lincat
    Phr = SyntaxIce.Phr ;
    NP  = SyntaxIce.NP ;
    CN  = SyntaxIce.CN ;
    Adv = SyntaxIce.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
