concrete WikiTMP of Wiki = open GrammarTMP, (P = ParadigmsTMP) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: TMP

  lincat
    Phr = GrammarTMP.Phr ;
    NP  = GrammarTMP.NP ;
    CN  = GrammarTMP.CN ;
    Adv = GrammarTMP.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
