concrete WikiEst of Wiki = open SyntaxEst, (P = ParadigmsEst) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Est

  lincat
    Phr = SyntaxEst.Phr ;
    NP  = SyntaxEst.NP ;
    CN  = SyntaxEst.CN ;
    Adv = SyntaxEst.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
