concrete WikiFin of Wiki = open SyntaxFin, (P = ParadigmsFin) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Fin

  lincat
    Phr = SyntaxFin.Phr ;
    NP  = SyntaxFin.NP ;
    CN  = SyntaxFin.CN ;
    Adv = SyntaxFin.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
