concrete WikiLit of Wiki = open GrammarLit, (P = ParadigmsLit) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Lit

  lincat
    Phr = GrammarLit.Phr ;
    NP  = GrammarLit.NP ;
    CN  = GrammarLit.CN ;
    Adv = GrammarLit.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
