concrete WikiMon of Wiki = open SyntaxMon, (P = ParadigmsMon) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Mon

  lincat
    Phr = SyntaxMon.Phr ;
    NP  = SyntaxMon.NP ;
    CN  = SyntaxMon.CN ;
    Adv = SyntaxMon.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
