concrete WikiSnd of Wiki = open SyntaxSnd, (P = ParadigmsSnd) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Snd

  lincat
    Phr = SyntaxSnd.Phr ;
    NP  = SyntaxSnd.NP ;
    CN  = SyntaxSnd.CN ;
    Adv = SyntaxSnd.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
