concrete WikiPnb of Wiki = open SyntaxPnb, (P = ParadigmsPnb) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Pnb

  lincat
    Phr = SyntaxPnb.Phr ;
    NP  = SyntaxPnb.NP ;
    CN  = SyntaxPnb.CN ;
    Adv = SyntaxPnb.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
