concrete WikiNor of Wiki = open SyntaxNor, (P = ParadigmsNor) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Nor

  lincat
    Phr = SyntaxNor.Phr ;
    NP  = SyntaxNor.NP ;
    CN  = SyntaxNor.CN ;
    Adv = SyntaxNor.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
