concrete WikiBel of Wiki = open GrammarBel, (P = ParadigmsBel) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Bel

  lincat
    Phr = GrammarBel.Phr ;
    NP  = GrammarBel.NP ;
    CN  = GrammarBel.CN ;
    Adv = GrammarBel.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
