concrete WikiKam of Wiki = open GrammarKam, (P = ParadigmsKam) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Kam

  lincat
    Phr = GrammarKam.Phr ;
    NP  = GrammarKam.NP ;
    CN  = GrammarKam.CN ;
    Adv = GrammarKam.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
