concrete WikiCze of Wiki = open SyntaxCze, (P = ParadigmsCze) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Cze

  lincat
    Phr = SyntaxCze.Phr ;
    NP  = SyntaxCze.NP ;
    CN  = SyntaxCze.CN ;
    Adv = SyntaxCze.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
