concrete WikiMay of Wiki = open SyntaxMay, (P = ParadigmsMay) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: May

  lincat
    Phr = SyntaxMay.Phr ;
    NP  = SyntaxMay.NP ;
    CN  = SyntaxMay.CN ;
    Adv = SyntaxMay.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
