concrete WikiSqi of Wiki = open GrammarSqi, (P = ParadigmsSqi) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Sqi

  lincat
    Phr = GrammarSqi.Phr ;
    NP  = GrammarSqi.NP ;
    CN  = GrammarSqi.CN ;
    Adv = GrammarSqi.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
