concrete WikiGla of Wiki = open GrammarGla, (P = ParadigmsGla) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Gla

  lincat
    Phr = GrammarGla.Phr ;
    NP  = GrammarGla.NP ;
    CN  = GrammarGla.CN ;
    Adv = GrammarGla.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
