concrete WikiKaz of Wiki = open GrammarKaz, (P = ParadigmsKaz) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Kaz

  lincat
    Phr = GrammarKaz.Phr ;
    NP  = GrammarKaz.NP ;
    CN  = GrammarKaz.CN ;
    Adv = GrammarKaz.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
