concrete WikiEus of Wiki = open SyntaxEus, (P = ParadigmsEus) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Eus

  lincat
    Phr = SyntaxEus.Phr ;
    NP  = SyntaxEus.NP ;
    CN  = SyntaxEus.CN ;
    Adv = SyntaxEus.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
