concrete WikiTur of Wiki = open SyntaxTur, (P = ParadigmsTur) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Tur

  lincat
    Phr = SyntaxTur.Phr ;
    NP  = SyntaxTur.NP ;
    CN  = SyntaxTur.CN ;
    Adv = SyntaxTur.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
