concrete WikiDut of Wiki = open SyntaxDut, (P = ParadigmsDut) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Dut

  lincat
    Phr = SyntaxDut.Phr ;
    NP  = SyntaxDut.NP ;
    CN  = SyntaxDut.CN ;
    Adv = SyntaxDut.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
