concrete WikiUrd of Wiki = open SyntaxUrd, (P = ParadigmsUrd) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Urd

  lincat
    Phr = SyntaxUrd.Phr ;
    NP  = SyntaxUrd.NP ;
    CN  = SyntaxUrd.CN ;
    Adv = SyntaxUrd.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
