concrete WikiMlt of Wiki = open SyntaxMlt, (P = ParadigmsMlt) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Mlt

  lincat
    Phr = SyntaxMlt.Phr ;
    NP  = SyntaxMlt.NP ;
    CN  = SyntaxMlt.CN ;
    Adv = SyntaxMlt.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
