concrete WikiRon of Wiki = open SyntaxRon, (P = ParadigmsRon) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Ron

  lincat
    Phr = SyntaxRon.Phr ;
    NP  = SyntaxRon.NP ;
    CN  = SyntaxRon.CN ;
    Adv = SyntaxRon.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
