concrete WikiAra of Wiki = open SyntaxAra, (P = ParadigmsAra) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Ara

  lincat
    Phr = SyntaxAra.Phr ;
    NP  = SyntaxAra.NP ;
    CN  = SyntaxAra.CN ;
    Adv = SyntaxAra.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
