concrete WikiSom of Wiki = open SyntaxSom, (P = ParadigmsSom) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Som

  lincat
    Phr = SyntaxSom.Phr ;
    NP  = SyntaxSom.NP ;
    CN  = SyntaxSom.CN ;
    Adv = SyntaxSom.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
