concrete WikiJpn of Wiki = open SyntaxJpn, (P = ParadigmsJpn) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Jpn

  lincat
    Phr = SyntaxJpn.Phr ;
    NP  = SyntaxJpn.NP ;
    CN  = SyntaxJpn.CN ;
    Adv = SyntaxJpn.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
