concrete WikiSwa of Wiki = open GrammarSwa, (P = ParadigmsSwa) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Swa

  lincat
    Phr = GrammarSwa.Phr ;
    NP  = GrammarSwa.NP ;
    CN  = GrammarSwa.CN ;
    Adv = GrammarSwa.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
