concrete WikiSpa of Wiki = open SyntaxSpa, (P = ParadigmsSpa) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Spa

  lincat
    Phr = SyntaxSpa.Phr ;
    NP  = SyntaxSpa.NP ;
    CN  = SyntaxSpa.CN ;
    Adv = SyntaxSpa.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
