concrete WikiKor of Wiki = open SyntaxKor, (P = ParadigmsKor) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Kor

  lincat
    Phr = SyntaxKor.Phr ;
    NP  = SyntaxKor.NP ;
    CN  = SyntaxKor.CN ;
    Adv = SyntaxKor.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
