concrete WikiCgg of Wiki = open GrammarCgg, (P = ParadigmsCgg) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Cgg

  lincat
    Phr = GrammarCgg.Phr ;
    NP  = GrammarCgg.NP ;
    CN  = GrammarCgg.CN ;
    Adv = GrammarCgg.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
