concrete WikiIna of Wiki = open SyntaxIna, (P = ParadigmsIna) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Ina

  lincat
    Phr = SyntaxIna.Phr ;
    NP  = SyntaxIna.NP ;
    CN  = SyntaxIna.CN ;
    Adv = SyntaxIna.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
