concrete WikiHeb of Wiki = open GrammarHeb, (P = ParadigmsHeb) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Heb

  lincat
    Phr = GrammarHeb.Phr ;
    NP  = GrammarHeb.NP ;
    CN  = GrammarHeb.CN ;
    Adv = GrammarHeb.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
