concrete WikiDan of Wiki = open SyntaxDan, (P = ParadigmsDan) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Dan

  lincat
    Phr = SyntaxDan.Phr ;
    NP  = SyntaxDan.NP ;
    CN  = SyntaxDan.CN ;
    Adv = SyntaxDan.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
