concrete WikiNno of Wiki = open SyntaxNno, (P = ParadigmsNno) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Nno

  lincat
    Phr = SyntaxNno.Phr ;
    NP  = SyntaxNno.NP ;
    CN  = SyntaxNno.CN ;
    Adv = SyntaxNno.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
