concrete WikiGus of Wiki = open GrammarGus, (P = ParadigmsGus) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Gus

  lincat
    Phr = GrammarGus.Phr ;
    NP  = GrammarGus.NP ;
    CN  = GrammarGus.CN ;
    Adv = GrammarGus.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
