concrete WikiHye of Wiki = open GrammarHye, (P = ParadigmsHye) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Hye

  lincat
    Phr = GrammarHye.Phr ;
    NP  = GrammarHye.NP ;
    CN  = GrammarHye.CN ;
    Adv = GrammarHye.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
