concrete WikiTam of Wiki = open SyntaxTam, (P = ParadigmsTam) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Tam

  lincat
    Phr = SyntaxTam.Phr ;
    NP  = SyntaxTam.NP ;
    CN  = SyntaxTam.CN ;
    Adv = SyntaxTam.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
