concrete WikiTel of Wiki = open GrammarTel, (P = ParadigmsTel) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Tel

  lincat
    Phr = GrammarTel.Phr ;
    NP  = GrammarTel.NP ;
    CN  = GrammarTel.CN ;
    Adv = GrammarTel.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
