concrete WikiSlv of Wiki = open GrammarSlv, (P = ParadigmsSlv) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Slv

  lincat
    Phr = GrammarSlv.Phr ;
    NP  = GrammarSlv.NP ;
    CN  = GrammarSlv.CN ;
    Adv = GrammarSlv.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
