concrete WikiAfr of Wiki = open SyntaxAfr, (P = ParadigmsAfr) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Afr

  lincat
    Phr = SyntaxAfr.Phr ;
    NP  = SyntaxAfr.NP ;
    CN  = SyntaxAfr.CN ;
    Adv = SyntaxAfr.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
