concrete WikiChi of Wiki = open SyntaxChi, (P = ParadigmsChi) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Chi

  lincat
    Phr = SyntaxChi.Phr ;
    NP  = SyntaxChi.NP ;
    CN  = SyntaxChi.CN ;
    Adv = SyntaxChi.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
