concrete WikiHin of Wiki = open SyntaxHin, (P = ParadigmsHin) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Hin

  lincat
    Phr = SyntaxHin.Phr ;
    NP  = SyntaxHin.NP ;
    CN  = SyntaxHin.CN ;
    Adv = SyntaxHin.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
