concrete WikiMkd of Wiki = open GrammarMkd, (P = ParadigmsMkd) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Mkd

  lincat
    Phr = GrammarMkd.Phr ;
    NP  = GrammarMkd.NP ;
    CN  = GrammarMkd.CN ;
    Adv = GrammarMkd.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
