concrete WikiZul of Wiki = open GrammarZul, (P = ParadigmsZul) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Zul

  lincat
    Phr = GrammarZul.Phr ;
    NP  = GrammarZul.NP ;
    CN  = GrammarZul.CN ;
    Adv = GrammarZul.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
