concrete WikiRus of Wiki = open SyntaxRus, (P = ParadigmsRus) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Rus

  lincat
    Phr = SyntaxRus.Phr ;
    NP  = SyntaxRus.NP ;
    CN  = SyntaxRus.CN ;
    Adv = SyntaxRus.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
