concrete WikiAmh of Wiki = open GrammarAmh, (P = ParadigmsAmh) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: SILVER
-- Language: Amh

  lincat
    Phr = GrammarAmh.Phr ;
    NP  = GrammarAmh.NP ;
    CN  = GrammarAmh.CN ;
    Adv = GrammarAmh.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
