concrete WikiPes of Wiki = open SyntaxPes, (P = ParadigmsPes) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Pes

  lincat
    Phr = SyntaxPes.Phr ;
    NP  = SyntaxPes.NP ;
    CN  = SyntaxPes.CN ;
    Adv = SyntaxPes.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
