concrete WikiHrv of Wiki = open SyntaxHrv, (P = ParadigmsHrv) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Hrv

  lincat
    Phr = SyntaxHrv.Phr ;
    NP  = SyntaxHrv.NP ;
    CN  = SyntaxHrv.CN ;
    Adv = SyntaxHrv.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
