concrete WikiHun of Wiki = open SyntaxHun, (P = ParadigmsHun) in {
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: GOLD
-- Language: Hun

  lincat
    Phr = SyntaxHun.Phr ;
    NP  = SyntaxHun.NP ;
    CN  = SyntaxHun.CN ;
    Adv = SyntaxHun.Adv ;

  lin
    SimpNP cn = mkNP a_Det cn ;
    
    John      = mkNP (P.mkPN "John") ;
    Here      = P.mkAdv "here" ; 
    apple_N   = mkCN (P.mkN "apple") ;
}
