"""Initial tables

Revision ID: 1807e0eccbca
Revises: 
Create Date: 2025-12-07 15:27:45.458731+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1807e0eccbca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORGANIZATION', 'PLACE', 'WORK', 'CONCEPT', 'OTHER', name='entity_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_slug'), 'entities', ['slug'], unique=True)
    op.create_table('generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('frame_slug', sa.String(length=128), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'ERROR', name='generation_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('nlg_engine', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_entity_id'), 'generations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_generations_frame_slug'), 'generations', ['frame_slug'], unique=False)
    op.create_index(op.f('ix_generations_id'), 'generations', ['id'], unique=False)
    op.create_index(op.f('ix_generations_request_id'), 'generations', ['request_id'], unique=False)
    op.create_index(op.f('ix_generations_status'), 'generations', ['status'], unique=False)
    op.create_table('generation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='generation_log_level_enum'), nullable=False),
    sa.Column('context', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_logs_created_at'), 'generation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_generation_logs_generation_id'), 'generation_logs', ['generation_id'], unique=False)
    op.create_index(op.f('ix_generation_logs_level'), 'generation_logs', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_logs_level'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_generation_id'), table_name='generation_logs')
    op.drop_index(op.f('ix_generation_logs_created_at'), table_name='generation_logs')
    op.drop_table('generation_logs')
    op.drop_index(op.f('ix_generations_status'), table_name='generations')
    op.drop_index(op.f('ix_generations_request_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_frame_slug'), table_name='generations')
    op.drop_index(op.f('ix_generations_entity_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_entities_slug'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###