import os
import json
import re

# --- Paths ---
# We assume this script runs from the project root context
ROOT_DIR = os.getcwd()
GF_DIR = "gf"
RGL_BASE = "gf-rgl/src"

# The Inventory "Fact Sheet" - Generated by rgl_scanner.py
# The Builder reads this to know exactly what modules exist for each language.
RGL_INVENTORY_FILE = os.path.join("data", "indices", "rgl_inventory.json")

# Fallback path if inventory is missing (for bootstrapping)
RGL_PATHS_FILE = "rgl_paths.json" 

# [NEW] Path to the Strategy Definitions
# This file defines the rules (Gold, Silver, Bronze, Iron)
STRATEGIES_FILE = os.path.join("builder", "strategies.json")

# --- RGL Families (Shared Resources) ---
# These folders contain shared definitions (like Romance.gf) that languages inherit from.
FAMILY_FOLDERS = [
    'romance', 'scandinavian', 'germanic', 'uralic', 
    'slavic', 'baltic', 'hindustani', 'arabic', 'turkic'
]

# --- Ambiguity Strategy ---
# "indef" = mkNP a_Det cn  (Safe, Standard) -> Forces "a cat" (prevents Mass Noun crashes)
# "mass"  = mkNP cn        (Risky) -> Tries "cat" (mass noun), crashes on languages like French/Finnish
AMBIGUITY_STRATEGY = "indef" 

# --- ISO / RGL Overrides ---
# Some languages have different codes in the RGL than their standard ISO codes.
# This map handles those exceptions to ensure we find the right files.
# Format: { "My_Preferred_Code": "RGL_Code" }
ISO_OVERRIDES = {
    "Deu": "Ger", # German
    "Bas": "Eus", # Basque
    "Ice": "Isl", # Icelandic
    "Rom": "Ron", # Romanian
    "Zho": "Chi", # Chinese
    "Jap": "Jpn"  # Japanese
}

def load_language_map():
    """
    Reads rgl_paths.json to dynamically build the map of available languages.
    Returns a dict: { "LangCode": "folder_name" }
    e.g., { "Afr": "afrikaans", "Eng": "english" }
    """
    if not os.path.exists(RGL_PATHS_FILE):
        # Fallback empty if file missing (orchestrator handles the error)
        return {}

    with open(RGL_PATHS_FILE, "r") as f:
        paths = json.load(f)

    lang_map = {}
    
    # regex to find "CatAfr" -> "Afr"
    # We look for keys starting with 'Cat' or 'Noun' to identify languages
    for module, relative_path in paths.items():
        # relative_path is like "afrikaans/CatAfr.gf"
        
        folder_name = os.path.dirname(relative_path)
        
        # Extract Code: CatAfr -> Afr
        code_match = re.search(r"(Cat|Noun)([A-Z][a-z]+)", module)
        if code_match:
            rgl_code = code_match.group(2)
            
            # Check for 3-letter standard (skip generic 'Romance', etc.)
            if len(rgl_code) >= 3:
                lang_map[rgl_code] = folder_name

    return lang_map

# Load immediately so other modules can import 'LANG_MAP'
LANG_MAP = load_language_map()