import os
import json
import glob
from . import config

def load_plan():
    """Loads the build plan generated by the Strategist."""
    plan_path = os.path.join("builder", "build_plan.json")
    if not os.path.exists(plan_path):
        return {}
    with open(plan_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def generate_abstract():
    """Generates the Abstract Grammar (Wiki.gf)."""
    # This remains static as it defines the API surface for all languages
    content = f"""abstract Wiki = {{
  flags startcat = Phr ;
  cat
    Phr ; NP ; CN ; Adv ;
  fun
    SimpNP : CN -> NP ;
    John : NP ;
    Here : Adv ;
    apple_N : CN ;
}}
"""
    if not os.path.exists(config.GF_DIR): os.makedirs(config.GF_DIR)
    
    path = os.path.join(config.GF_DIR, "Wiki.gf")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"   📄 Minted Abstract: {path}")

def execute_blueprint(rgl_code, blueprint):
    """
    Writes a concrete grammar file based strictly on the provided blueprint.
    No decision making happens here; only file I/O and formatting.
    """
    filename = f"Wiki{rgl_code}.gf"
    
    # Unpack the Blueprint
    # The blueprint contains pre-calculated strings for imports and rules
    imports = ", ".join(blueprint["imports"])
    lincats = blueprint["lincats"]
    rules = blueprint["rules"]
    status = blueprint["status"]

    # Construct File Content
    # We use .get() with defaults to prevent crashes if a rule is missing from the plan
    content = f"""concrete {filename[:-3]} of Wiki = open {imports} in {{
-- Generated by Forge v7 (Plan-Executor)
-- Strategy: {status}
-- Language: {rgl_code}

  lincat
    Phr = {lincats.get('Phr', 'Phr')} ;
    NP  = {lincats.get('NP', 'NP')} ;
    CN  = {lincats.get('CN', 'CN')} ;
    Adv = {lincats.get('Adv', 'Adv')} ;

  lin
    SimpNP cn = {rules.get('SimpNP', 'cn')} ;
    
    John      = {rules.get('John', 'SimpNP apple_N')} ;
    Here      = {rules.get('Here', 'SimpNP apple_N')} ; 
    apple_N   = {rules.get('apple_N', 'cn')} ;
}}
"""
    
    path = os.path.join(config.GF_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return True

def run():
    print("🏭 Factory Started: Executing Build Plan...")
    
    # 1. Load the Plan (The Instructions)
    plan = load_plan()
    if not plan:
        print("❌ Error: No build plan found. Run Strategist first.")
        return

    # 2. Clean Workspace (The Site Prep)
    if not os.path.exists(config.GF_DIR): os.makedirs(config.GF_DIR)
    for f in glob.glob(os.path.join(config.GF_DIR, "Wiki*.gf")):
        try: os.remove(f)
        except: pass

    # 3. Mint Abstract (The Foundation)
    generate_abstract()

    # 4. Execute Blueprints (The Construction)
    count = 0
    for rgl_code, blueprint in plan.items():
        execute_blueprint(rgl_code, blueprint)
        count += 1

    print(f"   ✨ Built {count} Grammars from Plan.")

if __name__ == "__main__":
    run()